Shared vehicle keys for jobs
qbcore-framework/qb-vehiclekeys pull request #155
Opened 2022-08-26 14:35 UTC by Re1ease

**Describe Pull request**
Allows the configuration of shared vehicle keys for job-listed vehicles. 

_Fixes the following enhancements;_
[127](https://github.com/qbcore-framework/qb-vehiclekeys/issues/127)
[117](https://github.com/qbcore-framework/qb-vehiclekeys/issues/117)

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **Yes.**
- Does your code fit the style guidelines? **Yes.**
- Does your PR fit the contribution guidelines? **Yes.**

2022-08-26 14:36 UTC, tom-osborne requested changes
Please use 4 spaces for indentation, not tab.

2022-08-26 14:58 UTC, Re1ease commented
> Please use 4 spaces for indentation, not tab.

Should be fixed.

2022-08-28 08:44 UTC, ChickenDipper1 commented
Tested and working - one issue found in that the player without keys will need to lock/unlock vehicle using L before they are able to turn on the engine.
If they do not do this first it will show the h to search keys.

2022-08-28 09:43 UTC, Re1ease commented
Thank you. 
I'll find a workaround on that part. I'll commit it tonight.

2022-08-28 11:30 UTC, Re1ease commented
> Tested and working - one issue found in that the player without keys will need to lock/unlock vehicle using L before they are able to turn on the engine. If they do not do this first it will show the h to search keys.

I tried replicating this @ChickenDipper1 but I couldn't.
Could you explain when the hotwiring would appear?

2022-08-28 11:34 UTC, Re1ease commented
> Tested and working - one issue found in that the player without keys will need to lock/unlock vehicle using L before they are able to turn on the engine. If they do not do this first it will show the h to search keys.

Fixed.

2022-08-28 11:35 UTC, ChickenDipper1 commented
Did you manage to replicate or do you need an example/demo?

2022-08-28 12:11 UTC, ChickenDipper1 approved these changes
Tested and working as expected.

2022-08-28 14:42 UTC, tom-osborne approved these changes

2022-08-28 14:42 UTC, merged

2022-08-28 15:47 UTC, ChickenDipper1 commented
Apologies it appears the change has caused hotwiring to not apply at all to any vehicles npc or otherwise and the options to have driving/npc cars locked no longer applies.

2022-08-28 15:59 UTC, Re1ease commented
> Apologies it appears the change has caused hotwiring to not apply at all to any vehicles npc or otherwise and the options to have driving/npc cars locked no longer applies.

I just tested this but wasn't able to replicate the error. Could you test it again with a fresh install?

2022-08-28 15:59 UTC, tom-osborne commented
@ChickenDipper1 still works for me. What config settings do you use?

2022-08-28 16:12 UTC, ChickenDipper1 commented
Sorry, all good it is working fine with a fresh install :)