fix(client/server): Fixes player vehicles locking when no driver present. Fixes #156
qbcore-framework/qb-vehiclekeys pull request #160
Opened 2022-09-07 18:52 UTC by tom-osborne

**Describe Pull request**
This PR has been created to address the issue of player vehicles unintentionally becoming locked after the owner leaves the vehicle. The NPC vehicle check logic did not cater for a player owned vehicle and treated any empty vehicle as an NPC vehicle, so when the config option `Config.LockNPCParkedCars` was set to `true` this would lock that vehicle when a player tried to enter the vehicle.

Fixes #156 & #159

This requires further testing. The following scenarios should be tested with `Config.LockNPCParkedCars = true`:  

**Scenario 1**  
1. Owner gets out of vehicle while vehicle is unlocked.
2. Other player without keys attempts to get in the vehicle.
**Expected result**: Both players should be able to enter the unlocked vehicle.

**Scenario 2**  
1. Owner locks vehicle from outside
2. Other player tries to enter. 
**Expected result**: Vehicle should be locked.

**Scenario 3**
1. Owner unlocks vehicle. 
2. Other player tries to enter empty vehicle.
**Expected result**: Vehicle should be unlocked

**Other tests**
- [ ] Lockpicking should remain as it was. (able to enter a vehicle NPC or owned after lock pick success)
- [ ] Config options for NPC cars should work as intended.
- [ ] Alternative config options should not affect Scenario's 1, 2 & 3

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-09-07 19:52 UTC, D4isDAVID requested changes
**Scenario 1** tested ok with a single exception - when using `/car` and leaving the vehicle without entering it again, `enteringEntity.state.playerOwned` remains nil for the other player that tries to enter and the vehicle gets locked.
**Scenario 2** tested fine.
**Scenario 3** tested fine.
Lockpicking remains as it was, being able to enter an owned or NPC vehicle after successfully lockpicking it.
The NPC vehicle locking options work as intended, and they do not affect the 3 scenarios.

2022-09-07 20:42 UTC, CptNoHand approved these changes
Scenario 1 works
Scenario 2 works.
Scenario 3 works.

That's actually amazing.

2022-09-07 21:04 UTC, CptNoHand commented
[script:qb-vehiclekey] SCRIPT ERROR: Invalid Lua type in __data
[script:qb-vehiclekey] > NetworkGetEntityFromNetworkId (NetworkGetEntityFromNetworkId.lua:2)
[script:qb-vehiclekey] > ref (@qb-vehiclekeys/server/main.lua:66)
[script:qb-vehiclekey] > TriggerCallback (@qb-core/server/functions.lua:253)
[script:qb-vehiclekey] > handler (@qb-core/server/events.lua:116)
[ script:qb-core] SCRIPT ERROR: error object is not a string

when someone goes near the car and is not the owner, this error appears in the live console, but everything still works

2022-09-08 21:43 UTC, jnccloud commented
> [script:qb-vehiclekey] SCRIPT ERROR: Invalid Lua type in __data [script:qb-vehiclekey] > NetworkGetEntityFromNetworkId (NetworkGetEntityFromNetworkId.lua:2) [script:qb-vehiclekey] > ref (@qb-vehiclekeys/server/main.lua:66) [script:qb-vehiclekey] > TriggerCallback (@qb-core/server/functions.lua:253) [script:qb-vehiclekey] > handler (@qb-core/server/events.lua:116) [ script:qb-core] SCRIPT ERROR: error object is not a string
> 
> when someone goes near the car and is not the owner, this error appears in the live console, but everything still works

Try this instead in server.lua:66

```lua
QBCore.Functions.CreateCallback("qb-vehiclekeys:server:checkPlayerOwned", function(_, cb, plate, vehNetId)
```

2022-09-09 00:11 UTC, CptNoHand commented
> > [script:qb-vehiclekey] SCRIPT ERROR: Invalid Lua type in __data [script:qb-vehiclekey] > NetworkGetEntityFromNetworkId (NetworkGetEntityFromNetworkId.lua:2) [script:qb-vehiclekey] > ref (@qb-vehiclekeys/server/main.lua:66) [script:qb-vehiclekey] > TriggerCallback (@qb-core/server/functions.lua:253) [script:qb-vehiclekey] > handler (@qb-core/server/events.lua:116) [ script:qb-core] SCRIPT ERROR: error object is not a string
> > when someone goes near the car and is not the owner, this error appears in the live console, but everything still works
> 
> Try this instead in server.lua:65
> 
> ```lua
> QBCore.Functions.CreateCallback("qb-vehiclekeys:server:checkPlayerOwned", function(_, cb, plate, vehNetId)
> ```

YES, now everything is perfect!

2022-09-09 02:33 UTC, jnccloud commented
> > > [script:qb-vehiclekey] SCRIPT ERROR: Invalid Lua type in __data [script:qb-vehiclekey] > NetworkGetEntityFromNetworkId (NetworkGetEntityFromNetworkId.lua:2) [script:qb-vehiclekey] > ref (@qb-vehiclekeys/server/main.lua:66) [script:qb-vehiclekey] > TriggerCallback (@qb-core/server/functions.lua:253) [script:qb-vehiclekey] > handler (@qb-core/server/events.lua:116) [ script:qb-core] SCRIPT ERROR: error object is not a string
> > > when someone goes near the car and is not the owner, this error appears in the live console, but everything still works
> > 
> > Try this instead in server.lua:65
> > 
> > ```lua
> > QBCore.Functions.CreateCallback("qb-vehiclekeys:server:checkPlayerOwned", function(_, cb, plate, vehNetId)
> > ```
> 
> YES, now everything is perfect!

Hmm are NPC cars locking for you?  I haven't tested with a full restart, but for me they were not locked and it's set to locked for both in the config

2022-09-09 02:47 UTC, CptNoHand commented
I just had a restart and tried and yes, you're right, they're not locked.

2022-09-09 02:48 UTC, CptNoHand commented
> Hmm are NPC cars locking for you?  I haven't tested with a full restart, but for me they were not locked and it's set to locked for both in the config

I just had a restart and tried and yes, you're right, they're not locked.

2022-09-09 08:30 UTC, tom-osborne commented
I'll work on an alternative solution. Thanks for testing guys

2022-09-09 08:30 UTC, closed without merging