🔑 Optionally save acquired keys into DB
qbcore-framework/qb-vehiclekeys pull request #255
Opened 2024-04-18 09:37 UTC by Cocodrulo

**Describe Pull request**
This PR makes so the aquired keys will be saved into DB so when the server restarts you will still have the keys you were given. This feature is optional and can be set in the Config file. The PR is made to answer this suggestion [[SUGGESTION] Database keys](https://github.com/qbcore-framework/qb-vehiclekeys/issues/253). I believe that is easier to make this into player metadata instead of a full new database table.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes

2024-05-04 17:15 UTC, KuulZone approved these changes

2024-05-04 17:16 UTC, KuulZone commented
Hopefully this gets in. It's kinda annoying.

2024-06-15 23:48 UTC, Z3rio commented
Lovely PR, and great idea.
But doing it this way is not recommended, as anyone could trigger that server event from their client with any kind of key list.

This should be something to be fully handled on the serverside if it should be secure.

2024-06-15 23:49 UTC, Z3rio requested changes
Lovely PR, and great idea.
But doing it this way is not recommended, as anyone could trigger that server event from their client with any kind of key list.

This should be something to be fully handled on the serverside if it should be secure.

2024-08-22 15:42 UTC, closed without merging

2024-11-13 23:13 UTC, Cocodrulo commented
I think this should be considered